sudo: required
language: python

addons:
  apt_packages:
  - pandoc

python:
- '2.7'
- '3.5'
- '3.6'

install:
- pip install -U pip
- pip install pypandoc
- pip install .[test]
- if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install .[async]; fi

script:
- pytest

branches:
  only: master

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git tag -a v$(python setup.py --version) -m "Travis build $TRAVIS_BUILD_NUMBER pushed
  a tag."
- git push origin --tags
- git fetch origin

deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist
    user: "trustpilot"
    password:
      secure: fo2BAlV19m/T1D9/ILcSlPZRxoH+8Zr9os0UKfsxBJNxFx/6W8ZF/Eh0uix0+8DCf/X+QogtVt59Up0hUBrBkW7n4RG1Af2wPg4jmdJBghpxPfodsAp9eetczOgyKcyoR4FcbbBEs7HmVbyeE7CnIoz3fo8pj7U6IWHZKNAlV8tLVjxDiitDMnNYMZIzaZWFRcG3/NfJafKaGInTkRq6NyNIr1zWOMiuw8Hhw+7LfSsKPbHFwP3h7B0AuE1dwZAAzQpxV8MbXZ9W2Z555DM+EQUQYHAnnbbwMjOoy2GQVKv87D7cLNANSHhTDJLZ8RvK2Eq8TeKCiWMAIfyM089J29R6yDHmylmUiHI2pu1cyDjCCNjwWp0qQApnDLCxV8ZkN2ezoANoDbxasT/1w05AdMSDxfAfZdu6tETpexJNqs9E4adlRWin0h0xEIvuPsZuIiEM6z3H7tcV6SPc8VKPqJ8iD3fFZJnXz2d5LZh7YMzWHiLmX0SfWoXj3XSgTCt6c5WHPdy2t0kqMOCWys17ZewnYF7ccTCOJEontkHhPrTGVVh13kcSRfdoJpfoDQOrvI2Rg09NTik22NYRTP9dUs/BUMBj7MHUEO+nzEqsRqGjjbySIJRHbfyz7cqwvkBmsRB6JzwfSEk5QEzjcFsszEaYq3osrVNjpmmd1WgXIP4=
    on:
      tags: false
      branch: master
      repo: trustpilot/python-trustpilot
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
  - provider: releases
    skip_cleanup: true
    api-key:
      secure: Msi7Ko/I5l+aJJszbBtUrER84PCag8YRiuAT9JNKCLwI+POmShrXhy9IAZg9Ot82lDrgiadExxhiFQPjiMGgZaT1N/akM30loE8PpsXdIKq+ChERFDj4QgZlhWnpQroeW/sefRCd9Bw8aInZyze84d0j9tv4zFP4aujlcHZmPdobUowJBp3RkotxWYNcRP+Viv/3fhChnth7eiLlRgNBBT/+yLKUWlE7gLzV4h/wjgv3aNnFtINTN72WT9DKyJs657+JGauRG6AMPCYhyYd0fA9O09JOd8l4S2/p6Sup7bfWUvyaYCQO8npSDo4s3LvPJbW+gTDOihJsysfojRf1n2HnvZt82xhDGbt9qNns7wDatxj4BmAl7LMVW2ON60c7hl8uZ170f0r7V9IqH4+az02FeZUXPPHVfc9+tSR6RSrZElL8RprNcy4f1jxW4drKeZKi6CGPjJAJ4x8kj985cj83kOc45SqxZH6vVojMOntgZez9dMKJUAbVIfRSs9dojf2OQYBCo/kysfv0+xck+VruPybuNhjCaCa5a21olSf6ZMO2EB7lXBr+AEeXF/Xth0cfEBUhBkCyuBFjsPhrXSENfsd3n4RhxST+sdy/oi0qMDYll4xVKSZRUGLoQljfpFJ1uWYdgmDa/xjCYxuZzy+IUXkXiKnCsfKKSYXc7Ms=
    file_glob: true
    file: dist/*
    on:
      tags: false
      branch: master
      repo: trustpilot/python-trustpilot
      condition: $TRAVIS_PYTHON_VERSION = "3.5"