language: python
python:
  - "3.7"
  - "3.8"
  # - "3.9" Not supported by travis yet
cache: pip

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry config virtualenvs.create false
  - poetry install --verbose

script:
  - poetry run black --check .
  - poetry run pytest -vvv tests

jobs:
  include:
    - stage: pypi
      python: "3.7"
      script: echo "Deploying to pypi ..."
      deploy:
        provider: script
        script: poetry publish --build
        on:
          branch: master

notifications:
  email: false
