sudo: required
language: python

addons:
  apt_packages:
  - pandoc

python:
- '2.7'
- '3.6'
- '3.7'

install:
- pip install -U pip
- pip install .[test] black
- if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install .[async]; fi

script:
- pytest
- black --check .

branches:
  only: master

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git tag -a v$(python setup.py --version) -m "Travis build $TRAVIS_BUILD_NUMBER pushed
  a tag."
- git push origin --tags
- git fetch origin