[tool.poetry]
name = "trustpilot"
version = "8.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.1"
requests = "^2.23.0"
aiohttp = "^3.6.2"
async_generator = "^1.10"

[tool.poetry.dev-dependencies]
responses = "^0.10.12"
mock = "^4.0.2"
pytest = "^5.4.1"
pytest-readme = "^1.0.0"
aioresponses = "^0.6.3"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
